### ISSUE TITLE
Build error for non-static HDF5 2.0.0 on Windows

### ISSUE THREAD

**Issue by jrydh** [metno/hdf5-rust#140]
On Windows, `hdf5-metno-sys` fails to build with a prebuilt HDF5 2.0.0 because the module in `h5fd.rs:493` is called `globals` and not `globals_2_0_0`.

```
error[E0432]: unresolved import `globals_2_0_0`
   --> [...]\hdf5-metno-sys-0.11.0\src\h5fd.rs:509:9
    |
509 | pub use globals_2_0_0::*;
    |         ^^^^^^^^^^^^^ use of unresolved module or unlinked crate `globals_2_0_0`
```
